/**
 * 皿打 - Sara-Da Typing Game
 * 単語データ（大幅拡張版）
 */

const WORDS = {
    easy: [
        // 動物
        { word: "ねこ", romaji: "neko" },
        { word: "いぬ", romaji: "inu" },
        { word: "さる", romaji: "saru" },
        { word: "とり", romaji: "tori" },
        { word: "うま", romaji: "uma" },
        { word: "かめ", romaji: "kame" },
        { word: "くま", romaji: "kuma" },
        { word: "りす", romaji: "risu" },
        { word: "うし", romaji: "usi" },
        { word: "ぶた", romaji: "buta" },
        { word: "ひつじ", romaji: "hituji" },
        { word: "やぎ", romaji: "yagi" },
        { word: "しか", romaji: "sika" },
        { word: "たぬき", romaji: "tanuki" },
        { word: "きつね", romaji: "kitune" },
        { word: "ねずみ", romaji: "nezumi" },
        // 自然
        { word: "そら", romaji: "sora" },
        { word: "うみ", romaji: "umi" },
        { word: "やま", romaji: "yama" },
        { word: "かわ", romaji: "kawa" },
        { word: "ほし", romaji: "hosi" },
        { word: "つき", romaji: "tuki" },
        { word: "はな", romaji: "hana" },
        { word: "きく", romaji: "kiku" },
        { word: "あめ", romaji: "ame" },
        { word: "ゆき", romaji: "yuki" },
        { word: "かぜ", romaji: "kaze" },
        { word: "くも", romaji: "kumo" },
        { word: "にじ", romaji: "niji" },
        { word: "いし", romaji: "isi" },
        { word: "すな", romaji: "suna" },
        // 時間・日常
        { word: "ひる", romaji: "hiru" },
        { word: "よる", romaji: "yoru" },
        { word: "あさ", romaji: "asa" },
        { word: "いま", romaji: "ima" },
        { word: "きのう", romaji: "kinou" },
        { word: "あした", romaji: "asita" },
        // 食べ物
        { word: "すし", romaji: "susi" },
        { word: "にく", romaji: "niku" },
        { word: "さけ", romaji: "sake" },
        { word: "みず", romaji: "mizu" },
        { word: "ちゃ", romaji: "tya" },
        { word: "かに", romaji: "kani" },
        { word: "えび", romaji: "ebi" },
        { word: "たこ", romaji: "tako" },
        { word: "いか", romaji: "ika" },
        { word: "まめ", romaji: "mame" },
        { word: "こめ", romaji: "kome" },
        { word: "むぎ", romaji: "mugi" },
        // 場所
        { word: "いえ", romaji: "ie" },
        { word: "まち", romaji: "mati" },
        { word: "みせ", romaji: "mise" },
        { word: "えき", romaji: "eki" },
        { word: "みち", romaji: "miti" },
        { word: "はし", romaji: "hasi" },
        // 体
        { word: "て", romaji: "te" },
        { word: "あし", romaji: "asi" },
        { word: "め", romaji: "me" },
        { word: "みみ", romaji: "mimi" },
        { word: "はな", romaji: "hana" },
        { word: "くち", romaji: "kuti" },
        // 色
        { word: "あか", romaji: "aka" },
        { word: "あお", romaji: "ao" },
        { word: "しろ", romaji: "siro" },
        { word: "くろ", romaji: "kuro" },
        { word: "きいろ", romaji: "kiiro" },
        { word: "みどり", romaji: "midori" }
    ],

    normal: [
        // 果物
        { word: "りんご", romaji: "ringo" },
        { word: "みかん", romaji: "mikan" },
        { word: "ぶどう", romaji: "budou" },
        { word: "いちご", romaji: "itigo" },
        { word: "ばなな", romaji: "banana" },
        { word: "もも", romaji: "momo" },
        { word: "なし", romaji: "nasi" },
        { word: "かき", romaji: "kaki" },
        { word: "すいか", romaji: "suika" },
        { word: "めろん", romaji: "meron" },
        { word: "れもん", romaji: "remon" },
        { word: "きうい", romaji: "kiui" },
        { word: "まんご", romaji: "mango" },
        { word: "さくらんぼ", romaji: "sakuranbo" },
        // 食べ物
        { word: "たまご", romaji: "tamago" },
        { word: "おにぎり", romaji: "onigiri" },
        { word: "らーめん", romaji: "ra-men" },
        { word: "うどん", romaji: "udon" },
        { word: "そば", romaji: "soba" },
        { word: "ぎょうざ", romaji: "gyouza" },
        { word: "てんぷら", romaji: "tenpura" },
        { word: "とんかつ", romaji: "tonkatu" },
        { word: "やきとり", romaji: "yakitori" },
        { word: "おでん", romaji: "oden" },
        { word: "なべ", romaji: "nabe" },
        { word: "かれー", romaji: "kare-" },
        // 花
        { word: "さくら", romaji: "sakura" },
        { word: "あじさい", romaji: "ajisai" },
        { word: "ひまわり", romaji: "himawari" },
        { word: "たんぽぽ", romaji: "tanpopo" },
        { word: "ちゅーりっぷ", romaji: "tyu-rippu" },
        { word: "ばら", romaji: "bara" },
        { word: "ゆり", romaji: "yuri" },
        { word: "こすもす", romaji: "kosumosu" },
        // 虫
        { word: "かぶとむし", romaji: "kabutomusi" },
        { word: "せみ", romaji: "semi" },
        { word: "ちょうちょ", romaji: "tyoutyo" },
        { word: "とんぼ", romaji: "tonbo" },
        { word: "ほたる", romaji: "hotaru" },
        { word: "かまきり", romaji: "kamakiri" },
        { word: "ばった", romaji: "batta" },
        { word: "てんとうむし", romaji: "tentoumusi" },
        // 乗り物
        { word: "でんしゃ", romaji: "densya" },
        { word: "ひこうき", romaji: "hikouki" },
        { word: "じてんしゃ", romaji: "jitensya" },
        { word: "くるま", romaji: "kuruma" },
        { word: "ばす", romaji: "basu" },
        { word: "たくしー", romaji: "takusi-" },
        { word: "ふね", romaji: "hune" },
        { word: "しんかんせん", romaji: "sinkansen" },
        { word: "ろけっと", romaji: "roketto" },
        { word: "へりこぷたー", romaji: "herikoputa-" },
        // 場所
        { word: "がっこう", romaji: "gakkou" },
        { word: "びょういん", romaji: "byouin" },
        { word: "こうえん", romaji: "kouen" },
        { word: "としょかん", romaji: "tosyokan" },
        { word: "えいがかん", romaji: "eigakan" },
        { word: "ゆうえんち", romaji: "yuuenti" },
        { word: "すいぞくかん", romaji: "suizokukan" },
        { word: "どうぶつえん", romaji: "doubutuen" },
        // 趣味
        { word: "えいが", romaji: "eiga" },
        { word: "おんがく", romaji: "ongaku" },
        { word: "からおけ", romaji: "karaoke" },
        { word: "げーむ", romaji: "ge-mu" },
        { word: "さっかー", romaji: "sakka-" },
        { word: "やきゅう", romaji: "yakyuu" },
        { word: "すいえい", romaji: "suiei" },
        { word: "まらそん", romaji: "marason" },
        { word: "てにす", romaji: "tenisu" },
        { word: "ごるふ", romaji: "goruhu" },
        { word: "ばすけ", romaji: "basuke" },
        { word: "ばどみんとん", romaji: "badominton" },
        // 職業
        { word: "せんせい", romaji: "sensei" },
        { word: "いしゃ", romaji: "isya" },
        { word: "かんごし", romaji: "kangosi" },
        { word: "けいさつ", romaji: "keisatu" },
        { word: "しょうぼうし", romaji: "syoubousi" },
        { word: "りょうり", romaji: "ryouri" }
    ],

    hard: [
        // テクノロジー
        { word: "ぷろぐらみんぐ", romaji: "puroguramingu" },
        { word: "こんぴゅーたー", romaji: "konpyu-ta-" },
        { word: "いんたーねっと", romaji: "inta-netto" },
        { word: "すまーとふぉん", romaji: "suma-tofon" },
        { word: "あぷりけーしょん", romaji: "apurike-syon" },
        { word: "でーたべーす", romaji: "de-tabe-su" },
        { word: "あるごりずむ", romaji: "arugorizumu" },
        { word: "ねっとわーく", romaji: "nettowa-ku" },
        { word: "そふとうぇあ", romaji: "sohutowea" },
        { word: "はーどうぇあ", romaji: "ha-dowea" },
        { word: "さーばー", romaji: "sa-ba-" },
        { word: "くらうど", romaji: "kuraudo" },
        // 建物・設備
        { word: "とらんぽりん", romaji: "toranporin" },
        { word: "えれべーたー", romaji: "erebe-ta-" },
        { word: "えすかれーたー", romaji: "esukare-ta-" },
        { word: "ぷらねたりうむ", romaji: "puranetariumu" },
        { word: "おぶざーばとりー", romaji: "obuzaba-tori-" },
        // 食べ物
        { word: "あいすくりーむ", romaji: "aisukuri-mu" },
        { word: "はんばーがー", romaji: "hanba-ga-" },
        { word: "ちょこれーと", romaji: "tyokore-to" },
        { word: "おむらいす", romaji: "omuraisu" },
        { word: "しゅーくりーむ", romaji: "syu-kuri-mu" },
        { word: "ぱんけーき", romaji: "panke-ki" },
        { word: "てぃらみす", romaji: "tiramisu" },
        { word: "ちーずけーき", romaji: "ti-zuke-ki" },
        { word: "くろわっさん", romaji: "kurowassan" },
        { word: "ぷりんあらもーど", romaji: "purinaramo-do" },
        // イベント
        { word: "くりすます", romaji: "kurisumasu" },
        { word: "ばれんたいん", romaji: "barentain" },
        { word: "はろうぃん", romaji: "harowin" },
        { word: "ひなまつり", romaji: "hinamaturi" },
        { word: "たなばた", romaji: "tanabata" },
        { word: "おしょうがつ", romaji: "osyougatu" },
        { word: "せつぶん", romaji: "setubun" },
        // 企業・ブランド
        { word: "まいくろそふと", romaji: "maikurosohuto" },
        { word: "あっぷる", romaji: "appuru" },
        { word: "にんてんどー", romaji: "nintendo-" },
        { word: "そにー", romaji: "soni-" },
        { word: "あまぞん", romaji: "amazon" },
        { word: "ぐーぐる", romaji: "gu-guru" },
        // ゲーム
        { word: "ぷれいすてーしょん", romaji: "pureisute-syon" },
        { word: "ぽけっともんすたー", romaji: "pokettomonsuta-" },
        { word: "どらごんくえすと", romaji: "doragonkuesuto" },
        { word: "ふぁいなるふぁんたじー", romaji: "fainaruhantazi-" },
        { word: "まりおかーと", romaji: "marioka-to" },
        { word: "すぷらとぅーん", romaji: "supuratu-n" },
        { word: "まいんくらふと", romaji: "mainkurahuto" },
        { word: "ふぉーとないと", romaji: "fo-tonaito" },
        // タイピング関連
        { word: "たいぴんぐ", romaji: "taipingu" },
        { word: "きーぼーど", romaji: "ki-bo-do" },
        { word: "ぶらいんどたっち", romaji: "buraindotatti" },
        { word: "たっちたいぴんぐ", romaji: "tattitaipingu" },
        // 形容詞・その他
        { word: "ぷろふぇっしょなる", romaji: "purofessyonaru" },
        { word: "あどべんちゃー", romaji: "adobentya-" },
        { word: "ふぁんたすてぃっく", romaji: "fantasuthikku" },
        { word: "えんたーていんめんと", romaji: "enta-teinmento" },
        { word: "いのべーしょん", romaji: "inobe-syon" },
        { word: "こみゅにけーしょん", romaji: "komyunike-syon" },
        { word: "ぷれぜんてーしょん", romaji: "purezente-syon" },
        { word: "あんびしゃす", romaji: "anbisyasu" },
        { word: "おぷてぃみすてぃっく", romaji: "oputimisuthikku" },
        { word: "ぺっしみすてぃっく", romaji: "pessimisuthikku" },
        // 動物（長い）
        { word: "かたつむり", romaji: "katatsumuri" },
        { word: "らいおん", romaji: "raion" },
        { word: "きりん", romaji: "kirin" },
        { word: "ぺんぎん", romaji: "pengin" },
        { word: "かんがるー", romaji: "kangaru-" },
        { word: "ふらみんご", romaji: "huramingo" },
        { word: "あるぱか", romaji: "arupaka" },
        { word: "ちんぱんじー", romaji: "tinpanji-" },
        { word: "おらんうーたん", romaji: "oranuu-tan" },
        { word: "ごりら", romaji: "gorira" }
    ]
};

// ランダムな単語を取得
function getRandomWord(difficulty) {
    const wordList = WORDS[difficulty];
    return wordList[Math.floor(Math.random() * wordList.length)];
}
